FROM registry-ds1.cnt.team:35000/webapp-test:v1.4

LABEL maintainer="Linkmuse Docker Maintainer <timur@cnt.team>"

WORKDIR /var/www/deployments/linkmuse-mobile.test.cnt.team

RUN npm install pm2 -g

COPY . /var/www/deployments/linkmuse-mobile.test.cnt.team/

# RUN ln -s public/dist/css linkmuse-webapp/dist && ln -s public/dist/img linkmuse-webapp/dist

# RUN chown -R www-data:www-data /var/www

# RUN php /var/www/deployments/webapp.test.cnt.team/artisan config:cache

# RUN rm .env

# RUN ln -s .env-test .env

# CMD /webapp-start.sh

EXPOSE 9001

#CMD ["npm", "run", "prod"]
CMD ["pm2-runtime", "ecosystem.config.js", "--only", "mobile-prod"]
