FROM registry-ds1.cnt.team:35000/webapp-test:v1.4

LABEL maintainer="Linkmuse Docker Maintainer <timur@cnt.team>"

WORKDIR /var/www/deployments/linkmuse-mobile.test.cnt.team

RUN npm install pm2 -g

COPY . /var/www/deployments/linkmuse-mobile.test.cnt.team/

EXPOSE 9001

#CMD ["npm", "run", "staging"]
CMD ["pm2-runtime", "ecosystem.config.js", "--only", "mobile-prod"]
