export const VIDEO_THUMBNAIL = '/dist/img/default_video.jpg'
export const PHOTO_THUMBNAIL = 'data:image/svg+xml;utf8,<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" version="1.1"><rect width="200" height="200" fill="#fff"/></svg>'
export const ACCEPT_PHOTO = 'image/*'
export const ACCEPT_VIDEO = 'video/*'
export const LABEL = 'Загрузить файл'
