export default {
  firstname: 'имя',
  lastname: 'фамилия',
  company_name: 'название компании',
  email: ' ',
  password: ' ',
  phone: 'телефон',
  'aboutme->birthday': 'дата рождения',
  'aboutme->guardian: ': 'имя родителя',
  'contactdetails->phone': 'телефон',
  'body-parameters->sex': 'пол',
  'user->phone': 'телефон',
  'user->fullname': 'ФИО',
  'user->company_name': 'название компании',
  'bank_account->itn': 'инн',
  'bank_account->iec': 'кпп',
  'bank_account->bic': 'бик',
  'bank_account->legal_address': 'юридический адрес',
  'bank_account->bank_recipient': 'банк-получатель',
  'bank_account->actual_address': 'фактический адрес',
  'bank_account->checking_account': 'расчетный счет',
  'bank_account->correspondent_account': 'кор. счет',
  date_start: 'Дата начала',
  date_end: 'Дата завершения',
  date_work_end: 'Дата завершения работы'
}
