export const CERTIFYING_SPECIALIST_APPROVED = 'certifying_specialist.approved'
export const CERTIFYING_SPECIALIST_ORDER_NEW = 'certifying_specialist.order.new'
export const CERTIFYING_SPECIALIST_ORDER_PAID = 'certifying_specialist.order.paid'
export const CERTIFYING_SPECIALIST_ORDER_CANCELED = 'certifying_specialist.order.canceled'
export const CERTIFYING_SPECIALIST_ORDER_FINISHED = 'certifying_specialist.order.stop_work'
export const CERTIFYING_SPECIALIST_ORDER_DISPUTE_OPENED = 'certifying_specialist.order.dispute_opened'
export const CERTIFYING_SPECIALIST_ORDER_CONFIRM_MEETING = 'certifying_specialist.order.confirm_meeting'
export const CERTIFYING_SPECIALIST_ORDER_DISPUTE_FINISHED = 'certifying_specialist.order.dispute_finished'
